# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/descriptor/openapiconfig/openapiconfig.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protoc_gen_openapiv2.options import openapiv2_pb2 as protoc__gen__openapiv2_dot_options_dot_openapiv2__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5internal/descriptor/openapiconfig/openapiconfig.proto\x12.grpc.gateway.internal.descriptor.openapiconfig\x1a,protoc-gen-openapiv2/options/openapiv2.proto\"e\n\x11OpenAPIFileOption\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x42\n\x06option\x18\x02 \x01(\x0b\x32\x32.grpc.gateway.protoc_gen_openapiv2.options.Swagger\"k\n\x13OpenAPIMethodOption\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x44\n\x06option\x18\x02 \x01(\x0b\x32\x34.grpc.gateway.protoc_gen_openapiv2.options.Operation\"j\n\x14OpenAPIMessageOption\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x41\n\x06option\x18\x02 \x01(\x0b\x32\x31.grpc.gateway.protoc_gen_openapiv2.options.Schema\"g\n\x14OpenAPIServiceOption\x12\x0f\n\x07service\x18\x01 \x01(\t\x12>\n\x06option\x18\x02 \x01(\x0b\x32..grpc.gateway.protoc_gen_openapiv2.options.Tag\"j\n\x12OpenAPIFieldOption\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x45\n\x06option\x18\x02 \x01(\x0b\x32\x35.grpc.gateway.protoc_gen_openapiv2.options.JSONSchema\"\xb7\x03\n\x0eOpenAPIOptions\x12O\n\x04\x66ile\x18\x01 \x03(\x0b\x32\x41.grpc.gateway.internal.descriptor.openapiconfig.OpenAPIFileOption\x12S\n\x06method\x18\x02 \x03(\x0b\x32\x43.grpc.gateway.internal.descriptor.openapiconfig.OpenAPIMethodOption\x12U\n\x07message\x18\x03 \x03(\x0b\x32\x44.grpc.gateway.internal.descriptor.openapiconfig.OpenAPIMessageOption\x12U\n\x07service\x18\x04 \x03(\x0b\x32\x44.grpc.gateway.internal.descriptor.openapiconfig.OpenAPIServiceOption\x12Q\n\x05\x66ield\x18\x05 \x03(\x0b\x32\x42.grpc.gateway.internal.descriptor.openapiconfig.OpenAPIFieldOption\"h\n\rOpenAPIConfig\x12W\n\x0fopenapi_options\x18\x01 \x01(\x0b\x32>.grpc.gateway.internal.descriptor.openapiconfig.OpenAPIOptionsBMZKgithub.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor/openapiconfigb\x06proto3')



_OPENAPIFILEOPTION = DESCRIPTOR.message_types_by_name['OpenAPIFileOption']
_OPENAPIMETHODOPTION = DESCRIPTOR.message_types_by_name['OpenAPIMethodOption']
_OPENAPIMESSAGEOPTION = DESCRIPTOR.message_types_by_name['OpenAPIMessageOption']
_OPENAPISERVICEOPTION = DESCRIPTOR.message_types_by_name['OpenAPIServiceOption']
_OPENAPIFIELDOPTION = DESCRIPTOR.message_types_by_name['OpenAPIFieldOption']
_OPENAPIOPTIONS = DESCRIPTOR.message_types_by_name['OpenAPIOptions']
_OPENAPICONFIG = DESCRIPTOR.message_types_by_name['OpenAPIConfig']
OpenAPIFileOption = _reflection.GeneratedProtocolMessageType('OpenAPIFileOption', (_message.Message,), {
  'DESCRIPTOR' : _OPENAPIFILEOPTION,
  '__module__' : 'internal.descriptor.openapiconfig.openapiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.openapiconfig.OpenAPIFileOption)
  })
_sym_db.RegisterMessage(OpenAPIFileOption)

OpenAPIMethodOption = _reflection.GeneratedProtocolMessageType('OpenAPIMethodOption', (_message.Message,), {
  'DESCRIPTOR' : _OPENAPIMETHODOPTION,
  '__module__' : 'internal.descriptor.openapiconfig.openapiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.openapiconfig.OpenAPIMethodOption)
  })
_sym_db.RegisterMessage(OpenAPIMethodOption)

OpenAPIMessageOption = _reflection.GeneratedProtocolMessageType('OpenAPIMessageOption', (_message.Message,), {
  'DESCRIPTOR' : _OPENAPIMESSAGEOPTION,
  '__module__' : 'internal.descriptor.openapiconfig.openapiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.openapiconfig.OpenAPIMessageOption)
  })
_sym_db.RegisterMessage(OpenAPIMessageOption)

OpenAPIServiceOption = _reflection.GeneratedProtocolMessageType('OpenAPIServiceOption', (_message.Message,), {
  'DESCRIPTOR' : _OPENAPISERVICEOPTION,
  '__module__' : 'internal.descriptor.openapiconfig.openapiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.openapiconfig.OpenAPIServiceOption)
  })
_sym_db.RegisterMessage(OpenAPIServiceOption)

OpenAPIFieldOption = _reflection.GeneratedProtocolMessageType('OpenAPIFieldOption', (_message.Message,), {
  'DESCRIPTOR' : _OPENAPIFIELDOPTION,
  '__module__' : 'internal.descriptor.openapiconfig.openapiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.openapiconfig.OpenAPIFieldOption)
  })
_sym_db.RegisterMessage(OpenAPIFieldOption)

OpenAPIOptions = _reflection.GeneratedProtocolMessageType('OpenAPIOptions', (_message.Message,), {
  'DESCRIPTOR' : _OPENAPIOPTIONS,
  '__module__' : 'internal.descriptor.openapiconfig.openapiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.openapiconfig.OpenAPIOptions)
  })
_sym_db.RegisterMessage(OpenAPIOptions)

OpenAPIConfig = _reflection.GeneratedProtocolMessageType('OpenAPIConfig', (_message.Message,), {
  'DESCRIPTOR' : _OPENAPICONFIG,
  '__module__' : 'internal.descriptor.openapiconfig.openapiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.openapiconfig.OpenAPIConfig)
  })
_sym_db.RegisterMessage(OpenAPIConfig)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZKgithub.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor/openapiconfig'
  _OPENAPIFILEOPTION._serialized_start=151
  _OPENAPIFILEOPTION._serialized_end=252
  _OPENAPIMETHODOPTION._serialized_start=254
  _OPENAPIMETHODOPTION._serialized_end=361
  _OPENAPIMESSAGEOPTION._serialized_start=363
  _OPENAPIMESSAGEOPTION._serialized_end=469
  _OPENAPISERVICEOPTION._serialized_start=471
  _OPENAPISERVICEOPTION._serialized_end=574
  _OPENAPIFIELDOPTION._serialized_start=576
  _OPENAPIFIELDOPTION._serialized_end=682
  _OPENAPIOPTIONS._serialized_start=685
  _OPENAPIOPTIONS._serialized_end=1124
  _OPENAPICONFIG._serialized_start=1126
  _OPENAPICONFIG._serialized_end=1230
# @@protoc_insertion_point(module_scope)
