# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal/descriptor/apiconfig/apiconfig.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import http_pb2 as google_dot_api_dot_http__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-internal/descriptor/apiconfig/apiconfig.proto\x12*grpc.gateway.internal.descriptor.apiconfig\x1a\x15google/api/http.proto\"0\n\x0eGrpcAPIService\x12\x1e\n\x04http\x18\x01 \x01(\x0b\x32\x10.google.api.HttpBIZGgithub.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor/apiconfigb\x06proto3')



_GRPCAPISERVICE = DESCRIPTOR.message_types_by_name['GrpcAPIService']
GrpcAPIService = _reflection.GeneratedProtocolMessageType('GrpcAPIService', (_message.Message,), {
  'DESCRIPTOR' : _GRPCAPISERVICE,
  '__module__' : 'internal.descriptor.apiconfig.apiconfig_pb2'
  # @@protoc_insertion_point(class_scope:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  })
_sym_db.RegisterMessage(GrpcAPIService)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZGgithub.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor/apiconfig'
  _GRPCAPISERVICE._serialized_start=116
  _GRPCAPISERVICE._serialized_end=164
# @@protoc_insertion_point(module_scope)
