// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal/descriptor/apiconfig/apiconfig.proto

#include "internal/descriptor/apiconfig/apiconfig.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace grpc {
namespace gateway {
namespace internal {
namespace descriptor {
namespace apiconfig {
constexpr GrpcAPIService::GrpcAPIService(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : http_(nullptr){}
struct GrpcAPIServiceDefaultTypeInternal {
  constexpr GrpcAPIServiceDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~GrpcAPIServiceDefaultTypeInternal() {}
  union {
    GrpcAPIService _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT GrpcAPIServiceDefaultTypeInternal _GrpcAPIService_default_instance_;
}  // namespace apiconfig
}  // namespace descriptor
}  // namespace internal
}  // namespace gateway
}  // namespace grpc
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto = nullptr;

const uint32_t TableStruct_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::grpc::gateway::internal::descriptor::apiconfig::GrpcAPIService, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::grpc::gateway::internal::descriptor::apiconfig::GrpcAPIService, http_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::grpc::gateway::internal::descriptor::apiconfig::GrpcAPIService)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::grpc::gateway::internal::descriptor::apiconfig::_GrpcAPIService_default_instance_),
};

const char descriptor_table_protodef_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n-internal/descriptor/apiconfig/apiconfi"
  "g.proto\022*grpc.gateway.internal.descripto"
  "r.apiconfig\032\025google/api/http.proto\"0\n\016Gr"
  "pcAPIService\022\036\n\004http\030\001 \001(\0132\020.google.api."
  "HttpBIZGgithub.com/grpc-ecosystem/grpc-g"
  "ateway/v2/internal/descriptor/apiconfigb"
  "\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto_deps[1] = {
  &::descriptor_table_google_2fapi_2fhttp_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto = {
  false, false, 247, descriptor_table_protodef_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto, "internal/descriptor/apiconfig/apiconfig.proto", 
  &descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto_once, descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto::offsets,
  file_level_metadata_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto, file_level_enum_descriptors_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto, file_level_service_descriptors_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto_getter() {
  return &descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto(&descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto);
namespace grpc {
namespace gateway {
namespace internal {
namespace descriptor {
namespace apiconfig {

// ===================================================================

class GrpcAPIService::_Internal {
 public:
  static const ::google::api::Http& http(const GrpcAPIService* msg);
};

const ::google::api::Http&
GrpcAPIService::_Internal::http(const GrpcAPIService* msg) {
  return *msg->http_;
}
void GrpcAPIService::clear_http() {
  if (GetArenaForAllocation() == nullptr && http_ != nullptr) {
    delete http_;
  }
  http_ = nullptr;
}
GrpcAPIService::GrpcAPIService(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
}
GrpcAPIService::GrpcAPIService(const GrpcAPIService& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_http()) {
    http_ = new ::google::api::Http(*from.http_);
  } else {
    http_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
}

inline void GrpcAPIService::SharedCtor() {
http_ = nullptr;
}

GrpcAPIService::~GrpcAPIService() {
  // @@protoc_insertion_point(destructor:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void GrpcAPIService::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete http_;
}

void GrpcAPIService::ArenaDtor(void* object) {
  GrpcAPIService* _this = reinterpret_cast< GrpcAPIService* >(object);
  (void)_this;
}
void GrpcAPIService::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void GrpcAPIService::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void GrpcAPIService::Clear() {
// @@protoc_insertion_point(message_clear_start:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && http_ != nullptr) {
    delete http_;
  }
  http_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* GrpcAPIService::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.api.Http http = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_http(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* GrpcAPIService::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.api.Http http = 1;
  if (this->_internal_has_http()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::http(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  return target;
}

size_t GrpcAPIService::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.api.Http http = 1;
  if (this->_internal_has_http()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *http_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData GrpcAPIService::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    GrpcAPIService::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GrpcAPIService::GetClassData() const { return &_class_data_; }

void GrpcAPIService::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<GrpcAPIService *>(to)->MergeFrom(
      static_cast<const GrpcAPIService &>(from));
}


void GrpcAPIService::MergeFrom(const GrpcAPIService& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_http()) {
    _internal_mutable_http()->::google::api::Http::MergeFrom(from._internal_http());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void GrpcAPIService::CopyFrom(const GrpcAPIService& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:grpc.gateway.internal.descriptor.apiconfig.GrpcAPIService)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GrpcAPIService::IsInitialized() const {
  return true;
}

void GrpcAPIService::InternalSwap(GrpcAPIService* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(http_, other->http_);
}

::PROTOBUF_NAMESPACE_ID::Metadata GrpcAPIService::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto_getter, &descriptor_table_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto_once,
      file_level_metadata_internal_2fdescriptor_2fapiconfig_2fapiconfig_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace apiconfig
}  // namespace descriptor
}  // namespace internal
}  // namespace gateway
}  // namespace grpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::grpc::gateway::internal::descriptor::apiconfig::GrpcAPIService* Arena::CreateMaybeMessage< ::grpc::gateway::internal::descriptor::apiconfig::GrpcAPIService >(Arena* arena) {
  return Arena::CreateMessageInternal< ::grpc::gateway::internal::descriptor::apiconfig::GrpcAPIService >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
